spring:
  datasource:
    url: jdbc:mysql:///to_do_list
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: true
      logic-delete-value: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: org.tai.todolist.dao
swagger:
  title: to-do-list
  description: 网页版to-do-list
  version: v2.0
  contact:
    name: Karigen
    email: 1837633996@qq.com
server:
  domain: http://localhost:8080
file:
  path: D:\images\
  prefix: /images/